# Generated by Django 6.0.3 on 2026-03-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('jssid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Endpoint', 'Endpoint')], default='Endpoint', max_length=50)),
                ('public_key', models.TextField()),
                ('ssh_port', models.IntegerField(editable=False)),
                ('vnc_port', models.IntegerField(editable=False)),
                ('last_checkin', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
