# Generated by Django 6.0.3 on 2026-03-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jssid', models.IntegerField(unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Endpoint', 'Endpoint')], default='Endpoint', max_length=50)),
                ('public_key', models.TextField()),
                ('ssh_port', models.IntegerField(editable=False, null=True)),
                ('vnc_port', models.IntegerField(editable=False, null=True)),
                ('last_checkin', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
