# Generated by Django 6.0.3 on 2026-03-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_computer_assigned_users_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jamf_url', models.URLField(blank=True, help_text='e.g., https://purdue.jamfcloud.com', max_length=255, null=True)),
                ('jamf_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('jamf_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('jamf_laps_enabled', models.BooleanField(default=False)),
                ('agent_checkin_interval_minutes', models.IntegerField(default=60)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('auto', 'System Default'), ('light', 'Light Mode'), ('dark', 'Dark Mode')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='America/Indiana/Indianapolis', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Server Administrator', 'Server Administrator'), ('Desktop Administrator', 'Desktop Administrator'), ('Customer', 'Customer'), ('Unassigned', 'Unassigned')], default='Customer', max_length=50),
        ),
    ]
