# Generated by Django 6.0.3 on 2026-03-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_globalsettings_userprofile_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='macoslaps_ea_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='prestage_laps_type',
            field=models.CharField(choices=[('jamf', 'Jamf Built-in LAPS'), ('macoslaps', 'macOSLAPS (Extension Attribute)')], default='jamf', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=50),
        ),
    ]
