# Generated by Django 6.0.3 on 2026-03-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_globalsettings_macoslaps_ea_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='last_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='primary_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='jamf_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='Customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
