# Generated by Django 6.0.3 on 2026-03-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_computer_last_user_computer_primary_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='custom_server_port',
            field=models.IntegerField(default=9922),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='custom_server_port_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
